### ISSUE TITLE
Unable to open project

### ISSUE THREAD

**Issue by pr0te** [bscotch/stitch#169]
Hi! I'm just here to try out Stitch, coming from GMEdit. I'm unable to load my project and I have a bunch of errors in the log.

`ERROR 11:50:54.291 ERROR: Error reading file: c:/Git/Bobls2020/objects/obj_player/obj_player.yy
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "null",
    "path": [
      "properties",
      0,
      "listItems"
    ],
    "message": "Expected array, received null"
  }
]
Error: Error reading file: c:/Git/Bobls2020/objects/obj_player/obj_player.yy
[
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "null",
    "path": [
      "properties",
      0,
      "listItems"
    ],
    "message": "Expected array, received null"
  }
]
	at Yy.read (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:22184:25)
	at async _Asset.readYy (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:40642:19)
	at async _Asset.reload (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:40715:11)
	at async Asset.from (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:40845:9)
	at async Promise.all (index 109)
	at async _GameMakerProject.loadAssets (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:65887:29)
	at async _GameMakerProject.initialize (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:65987:24)
	at async GameMakerProject.from (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:106086:9)
	at async c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:106182:23
  CAUSE: [
  {
    "code": "invalid_type",
    "expected": "array",
    "received": "null",
    "path": [
      "properties",
      0,
      "listItems"
    ],
    "message": "Expected array, received null"
  }
]
  ZodError: [
    {
      "code": "invalid_type",
      "expected": "array",
      "received": "null",
      "path": [
        "properties",
        0,
        "listItems"
      ],
      "message": "Expected array, received null"
    }
  ]
  	at get error [as error] (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:17267:27)
  	at _ZodObject.parse (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:17351:22)
  	at parseYy (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:20732:26)
  	at Yy.parse (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:22178:16)
  	at Yy.read (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:22182:22)
  	at async _Asset.readYy (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:40642:19)
  	at async _Asset.reload (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:40715:11)
  	at async Asset.from (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:40845:9)
  	at async Promise.all (index 109)
  	at async _GameMakerProject.loadAssets (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:65887:29)
  	at async _GameMakerProject.initialize (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:65987:24)
  	at async GameMakerProject.from (c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:106086:9)
  	at async c:\Users\tnl\.vscode\extensions\bscotch.bscotch-stitch-vscode-1.51.4\dist\extension.js:106182:23`
  	
 As well as a lot of these:
 
 `ERROR 11:50:54.296 Error loading project c:\Git\Bobls2020\Bobls2030.yyp
INFO 11:50:54.309 Extension activated in 1.252 seconds
DEBUG 11:50:54.534 [PARSER] SYNTAX ERROR Expecting: one of these possible Token sequences:
  1. [BooleanLiteral]
  2. [NumericLiteral]
  3. [PointerLiteral]
  4. [Undefined]
  5. [NaN]
  6. [StringStart]
  7. [MultilineDoubleStringStart]
  8. [MultilineSingleStringStart]
  9. [TemplateStart]
  10. [New]
  11. [Identifier]
  12. [Self]
  13. [Other]
  14. [Global]
  15. [Noone]
  16. [All]
  17. [StartParen]
  18. [StartBracket]
but found: ';' c:/Git/Bobls2020/objects/obj_control/Create_0.gml {"image":";","startOffset":1013,"endOffset":1013,"startLine":44,"endLine":44,"startColumn":16,"endColumn":16,"tokenTypeIdx":128,"tokenType":{"name":"Semicolon","PATTERN":{},"CATEGORIES":[{"name":"Separators","PATTERN":{},"tokenTypeIdx":20,"CATEGORIES":[],"categoryMatches":[33,34,35,36,45,46,106,107,108,109,110,127,128,131,132,133,134,135,136,137,138,144,146,148,149,151],"categoryMatchesMap":{"33":true,"34":true,"35":true,"36":true,"45":true,"46":true,"106":true,"107":true,"108":true,"109":true,"110":true,"127":true,"128":true,"131":true,"132":true,"133":true,"134":true,"135":true,"136":true,"137":true,"138":true,"144":true,"146":true,"148":true,"149":true,"151":true},"isParent":true}],"tokenTypeIdx":128,"categoryMatches":[],"categoryMatchesMap":{},"isParent":false}}`

Anything we can do to solve this?

**Comment by adam-coster** [comment]
Thanks for the report!

The issue preventing you from opening your project should be resolved as of extension v1.51.5 (publishing now).

(There was a field in the yy files that I've only ever seen as an array, but apparently it can also be `null`. Might be a new thing!)

Regarding the SYNTAX ERROR:

It looks like you're using some kind of syntax that Stitch doesn't support (it doesn't support *everything* that GML allows). Without seeing the GML that's giving you this error I can't guess what the problem is, though if you're doing anything interesting with macros that's a likely culprit.

Once you can boot the project you should be able to see the errors in context with your code, so then you can provide me a sample of the GML that's giving you the syntax errors. You can re-open this issue in that case!

**Comment by pr0te** [comment]
Thank you so much. The project loads now. Still haven't been able to pinpoint the syntax error from the log. Will get back if I'm able to make sense of it.

**Comment by adam-coster** [comment]
If you open up the Problems panel you should be able to see where the syntax errors are happening, though there could be a lot of issues listed there!

**Comment by pr0te** [comment]
Ah yes, I got 6900+ problems but a... Anyway, I tried to go directly after what was logged upon loading the project, which lead me to random pieces of code with no problems. I can however find them in the Problems panel.

One of them is this array of strings, where one of the entries have been commented out.
https://i.imgur.com/aYR9M8T.png

And this one from the Input framework by JuJu Adams. (There are a bunch of these)
https://i.imgur.com/WdBWRUd.png

**Comment by adam-coster** [comment]
Huh, that comments one is weird. I wonder if it's because it's a `////` instead of the usual `//` or `///` comment. I'll have to dig into that.

That second one is a known issue where Stitch can't parse [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE)-like syntax nor macros that do anything interesting.
