### ISSUE TITLE
Parsing extensions that includes signifiers defined in GML Spec causes conflict and project loading failure

### ISSUE THREAD

**Issue by shichen85** [bscotch/stitch#191]
GameMaker migrated some of the platform specific functions into extensions. An example is the `xboxone_*` functions defined in `runtime-*/xboxseriesxs/GmlSpec.xml` are now moved to [the GDK extension](https://github.com/YoYoGames/GDKExtension). These functions are no longer packed in the runtime but still defined in the GmlSpec.xml file, so when Stitch parses both the Spec file and the extension file, it runs into the "Cannot replace existing member with new member" error:

https://github.com/bscotch/stitch/blob/d99644f40a4f62ef5246acea76a1adcfb7755842/packages/parser/src/types.ts#L407

A possible solution is when adding assets that are extension, we flag the override option:

https://github.com/bscotch/stitch/blob/d99644f40a4f62ef5246acea76a1adcfb7755842/packages/parser/src/project.asset.ts#L76

**Comment by adam-coster** [comment]
The GmlSpec is the best source for the signifier, assuming it contains an accurate signature and description. So if those functions are in the spec, and the spec gets loaded first, then we'd be overriding the spec version with the less-accurate information that comes out of the extension files. Or that's how I understand the situation anyway.

So I don't quite understand what the problem is that you're wanting to solve here. Is it that you want the extension to override the spec, or is there spurious error output that is creating confusion/breaking something?

**Comment by shichen85** [comment]
The main problem is that the extension fails to load the project if the project contains extensions that define functions that are already declared in GmlSpec. For example, the function `xboxone_check_privilege()` is defined in both the GDKExtension.yy and in `runtime-*/xboxseriesxs/GmlSpec.xml`, so when loading the project, the extension would fail with the following error:

```
INFO 14:47:50.471 Activating extension...
INFO 14:47:50.478 Activating extension...
INFO 14:47:50.479 Loading projects...
INFO 14:47:52.972 Loading project e:\repos\Games\crashlands\Crashlands\Crashlands.yyp
INFO 14:47:52.973 [PARSER] Initializing project...
INFO 14:47:52.973 [PARSER] Loading asset files...
INFO 14:47:52.998 [PARSER] Found stitch config
INFO 14:47:53.480 [PARSER] Loaded yyp file!
WARN 14:47:53.481 [PARSER] No stitch config found, looking up runtime version
INFO 14:47:56.323 [PARSER] Looking for spec files in "c:/ProgramData/GameMakerStudio2-Beta/Cache/runtimes/runtime-2023.1100.0.459"
INFO 14:47:57.020 [PARSER] Loading spec for module Base
WARN 14:47:57.062 [PARSER] Native function static_get already exists, skipping.
WARN 14:47:57.068 [PARSER] Native function display_get_frequency already exists, skipping.
INFO 14:47:57.068 [PARSER] Loading spec for module switch
INFO 14:47:57.070 [PARSER] Loading spec for module xboxseriesxs
INFO 14:47:57.075 [PARSER] Loaded GML spec in 4102ms
ERROR 14:48:17.469 [PARSER] ERROR: Cannot replace existing member with new member
StitchParserError: Cannot replace existing member with new member
    at _Type.addMember (c:\Users\shi\.vscode-insiders\extensions\parser\src\types.ts:403:5)
    at _Asset.reload (c:\Users\shi\.vscode-insiders\extensions\parser\src\project.asset.ts:539:31)
    at Function.from (c:\Users\shi\.vscode-insiders\extensions\parser\src\project.asset.ts:667:5)
    at async Promise.all (index 5001)
    at _GameMakerProject.loadAssets (c:\Users\shi\.vscode-insiders\extensions\parser\src\project.ts:699:25)
    at _GameMakerProject.initialize (c:\Users\shi\.vscode-insiders\extensions\parser\src\project.ts:882:20)
    at Function.from (c:\Users\shi\.vscode-insiders\extensions\bscotch.bscotch-stitch-vscode-1.55.15\src\extension.project.mts:185:5)
    at c:\Users\shi\.vscode-insiders\extensions\bscotch.bscotch-stitch-vscode-1.55.15\src\extension.workspace.mts:100:19
```

In the case of Xbox related functions, the GmlSpec is actually incorrect because those functions are moved out of the runtime and now lives in the GDK extension.

I filed [an issue](https://github.com/YoYoGames/GameMaker-Bugs/issues/2454) to GameMaker to update their GmlSpec files, but before they publish a correct version, we still need to resolve the conflict of extensions containing signifiers declared in GmlSpec.

**Comment by adam-coster** [comment]
Ah, that's what we were trying to fix in the update on Friday. Somehow that didn't resolve the problem I guess. Have you been able to track down why this error makes it through the try/catch logic we added? Or is this error somewhere outside of the extension-loading logic?

**Comment by shichen85** [comment]
I am guessing that we put the try/catch logic in reload() 
https://github.com/bscotch/stitch/blob/b2151d2c8af54e86e9d9b1810621ce678383488b/packages/parser/src/project.asset.ts#L457

But the exception might happened earlier at the Asset constructor initialization: https://github.com/bscotch/stitch/blob/b2151d2c8af54e86e9d9b1810621ce678383488b/packages/parser/src/project.asset.ts#L75

**Comment by adam-coster** [comment]
Hmmmm. The solution we should have here is that:

- The extension *does* still get loaded
- When the extension is being loaded, if its functions/constants are found to conflict with existing globals (presumably from the spec), then we just skip over those ones

I don't have the bandwidth to sort that out today, but if I can replicate the problem locally I ought to be able to fix it tomorrow.

**Comment by shichen85** [comment]
The replication is to load a project that has the GDK extension in it. I can take a crack at it.

**Comment by shichen85** [comment]
> I am guessing that we put the try/catch logic in reload()
> 
> https://github.com/bscotch/stitch/blob/b2151d2c8af54e86e9d9b1810621ce678383488b/packages/parser/src/project.asset.ts#L457
> 
> But the exception might happened earlier at the Asset constructor initialization:
> 
> https://github.com/bscotch/stitch/blob/b2151d2c8af54e86e9d9b1810621ce678383488b/packages/parser/src/project.asset.ts#L75

Never mind, the error was thrown in the reload() block. It was the Diagnostic emit that went wrong:

```
Stitch ERROR 18:58:15.325 ERROR: Illegal argument: line must be non-negative
Error: Illegal argument: line must be non-negative
	at m (e:\Users\shi\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:10:1101)
	at new f (e:\Users\shi\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:139:4458)
	at e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:66851:7
	at logThrown (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:15616:12)
	at rangeFrom (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:66849:10)
	at e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:67043:12
	at Array.map (<anonymous>)
	at normalizeDiagnosticsEvents (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:67041:30)
	at _StitchWorkspace.emitDiagnostics (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:106565:11)
	at EventEmitter.emit (node:events:514:28)
	at _GameMakerProject.emitDiagnostics (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:65808:22)
	at _Asset.reload (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:41016:24)
	at async Asset.from (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:41096:9)
	at async Promise.all (index 2)
	at async _GameMakerProject.loadAssets (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:66208:29)
	at async _GameMakerProject.initialize (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:66336:24)
	at async GameMakerProject.from (e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:106492:9)
	at async e:\repos\ThirdParty\stitch\packages\vscode\dist\extension.js:106588:23
```
