### ISSUE TITLE
Drag-and-drop to create new Sprites no longer generates a correct .yy file, resulting in a failure to compile.

### ISSUE THREAD

**Issue by BscotchSeth** [bscotch/stitch#238]
It looks like it's expecting a .yy field called `builtinName`.

```
c:/GameDev/CL2/Crashlands2/sprites/sp_keyboard_rightarrow/sp_keyboard_rightarrow.yy(70,34): GMSC Error: builtinName expected.
Core Resources : IDE Message - ProjectLoad_ErrorTitle : ProjectLoad_ErrorMessage ( c:/GameDev/CL2/Crashlands2/sprites/sp_keyboard_rightarrow/sp_keyboard_rightarrow.yy(70,34): GMSC Error: builtinName expected. )
Unhandled exception. 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GMAssetCompiler.Loader.<>c__DisplayClass5_0.b__2(ResourceBase _project)
   at YoYoStudio.Resources.ProjectInfo.<>c__DisplayClass23_0.g__handleFailure|4(String message) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Management/ProjectInfo.cs:line 294
   at YoYoStudio.Resources.ProjectInfo.LoadProject(String _path, Boolean _setActive, OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed, Boolean _triedProjectTool) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Management/ProjectInfo.cs:line 322
   at GMAssetCompiler.Loader.LoadGMS2CreateAssets(String _filename)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
```

**Comment by adam-coster** [comment]
This was due to the `%Name` field not getting properly deleted from an internal object in the Sprite YY file. GameMaker now assumes fields will appear in a specific order, so it expected a field to be `builtinName` but found `%Name` -- `builtinName` was in the object, it was just the *next* key.

Should be resolved in `1.68.4`
