### ISSUE TITLE
No constructor for resource "particles"

### ISSUE THREAD

**Issue by adam-coster** [bscotch/stitch#49]
The latest GameMaker versions include a new "Particle" resource type, which is currently not implemented in Stitch.

Two options for resolving this issue:
1. Add the Particle type to Stitch
2. Add a fallback type to Stitch for unknown resource types (more future-compatible)

Reported in IDE v2023.2.1.75 Runtime v2023.2.1.90

```
stitch add sprites --source=\sprite_root --flatten --debug
Running in debug mode

loading project with options
    projectPath: g:/GameMakerStudio2/Shredders_2/Shredders_2.yyp

file:///{...path}/node_modules/@bscotch/stitch/dist/lib/components/Gms2ResourceArray.js:240
            throw new StitchError(`No constructor for resource ${resourceType} exists.`);
                  ^

StitchError: No constructor for resource particles exists.
    at Function.hydrateResource (file:///{...path}/node_modules/@bscotch/stitch/dist/lib/components/Gms2ResourceArray.js:240:19)
    at file:///{...path}/node_modules/@bscotch/stitch/dist/lib/components/Gms2ResourceArray.js:31:59
    at Array.map (<anonymous>)
    at new Gms2ResourceArray (file:///{...path}/node_modules/@bscotch/stitch/dist/lib/components/Gms2ResourceArray.js:31:27)
    at StitchProject.reload (file:///{...path}/node_modules/@bscotch/stitch/dist/lib/StitchProject.js:539:24)
    at async Function.load (file:///{...path}/node_modules/@bscotch/stitch/dist/lib/StitchProject.js:66:9)
    at async default (file:///{...path}/node_modules/@bscotch/stitch/dist/cli/lib/add-sprites.js:7:27)
```

**Comment by adam-coster** [comment]
Closed by fceb4053eb3e56a7aab6c0b22b57a1460e3f55cc
